ARG UBUNTU_VERSION=22.04

FROM ubuntu:${UBUNTU_VERSION}

ENV DEBIAN_FRONTEND noninteractive

# Install common dependencies
COPY ./common/install_base.sh install_base.sh
RUN bash ./install_base.sh && rm install_base.sh

# Install cuda, cudnn and nccl
ARG CUDA_VERSION=12.1
RUN wget -q https://raw.githubusercontent.com/pytorch/builder/main/common/install_cuda.sh -O install_cuda.sh
RUN bash ./install_cuda.sh ${CUDA_VERSION} && rm install_cuda.sh
ENV DESIRED_CUDA ${CUDA_VERSION}
ENV PATH /usr/local/nvidia/bin:/usr/local/cuda/bin:$PATH

# Install gcc
ARG GCC_VERSION=12
RUN apt-get update \
    && apt-get install -y --no-install-recommends \
    software-properties-common gpg-agent
COPY ./common/install_gcc.sh install_gcc.sh
RUN bash ./install_gcc.sh && rm install_gcc.sh

ARG CMAKE_VERSION=3.18.5
COPY ./common/install_cmake.sh install_cmake.sh
RUN if [ -n "${CMAKE_VERSION}" ]; then bash ./install_cmake.sh; fi
RUN rm install_cmake.sh

ARG NINJA_VERSION=1.9.0
COPY ./common/install_ninja.sh install_ninja.sh
RUN if [ -n "${NINJA_VERSION}" ]; then bash ./install_ninja.sh; fi
RUN rm install_ninja.sh

# Install python
COPY ./common/install_python.sh install_python.sh
RUN bash ./install_python.sh "3.9.18"
RUN bash ./install_python.sh "3.10.13"
RUN apt-get update \
    && apt-get install -y --no-install-recommends \
    zlib1g-dev libncurses5-dev libgdbm-dev libnss3-dev \
    libssl-dev libreadline-dev libffi-dev libsqlite3-dev wget libbz2-dev
# RUN bash ./install_python.sh "3.12.0"
# RUN bash ./install_python.sh "3.11.6"
RUN rm install_python.sh
# RUN apt-get update \
#     && add-apt-repository ppa:deadsnakes/ppa \
#     && apt-get install -y \
#     python-is-python3 \
# # +   python-dev-is-python3 \
#     python3-pip \
#     python3.8 \
#     python3.8-dev \
#     python3.9 \
#     python3.9-dev \
#     python3.10 \
#     python3.10-dev \
#     python3.11 \
#     python3.11-dev 

CMD ["bash"]