name: Create Release
on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to build and update whl index'
        required: true
        type: string

  workflow_call:
    inputs:
      tag:
        description: 'Tag to build and update whl index'
        required: true
        type: string

env:
  # Tells where to store caches.
  CI_CACHE_DIR: ${{ github.workspace }}/../../ci_cache

jobs:
  build_wheel:
    strategy:
      fail-fast: false
      matrix:
        python: ["3.9", "3.10", "3.11", "3.12", "3.13"]
        cuda: ["12.6", "12.8", "12.9"]
        torch: ["2.8.0"]
    runs-on: [self-hosted, linux]
    env:
      PYTHON_VERSION: ${{ matrix.python }}
      CUDA_VERSION: ${{ matrix.cuda }}
      TORCH_VERSION: ${{ matrix.torch }}
      SCALELLM_VERSION: ${{ inputs.tag }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Create cache directory
        run: |
          mkdir -p $CI_CACHE_DIR/.vcpkg/bincache
          mkdir -p $CI_CACHE_DIR/.ccache
          mkdir -p $CI_CACHE_DIR/.pip

      - name: Delete old files
        run: rm -rf dist/*

      - name: Build wheel
        timeout-minutes: 60
        run: |
          docker pull vectorchai/scalellm_manylinux2_28:cuda${CUDA_VERSION}
          docker run --rm -t \
              -v "$CI_CACHE_DIR":/ci_cache \
              -v "$GITHUB_WORKSPACE":/ScaleLLM \
              -e PYTHON_VERSION=${PYTHON_VERSION} \
              -e CUDA_VERSION=${CUDA_VERSION} \
              -e TORCH_VERSION=${TORCH_VERSION} \
              -e SCALELLM_VERSION=${SCALELLM_VERSION} \
              -e SCALELLM_VERSION_SUFFIX="+cu${CUDA_VERSION//./}torch${TORCH_VERSION}" \
              -e VCPKG_DEFAULT_BINARY_CACHE=/ci_cache/.vcpkg/bincache \
              -e CCACHE_DIR=/ci_cache/.ccache \
              -e PIP_CACHE_DIR=/ci_cache/.pip \
              -u $(id -u):$(id -g) \
              vectorchai/scalellm_manylinux2_28:cuda${CUDA_VERSION} \
              bash /ScaleLLM/.ci/scripts/build_wheel.sh

      - name: show wheel size
        run: du -h dist/*

      - uses: actions/upload-artifact@v4
        with:
          name: wheel-cuda${{ matrix.cuda }}-torch${{ matrix.torch }}-python${{ matrix.python }}
          path: dist/*

  create_release:
    needs: build_wheel
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Delete old files
        run: rm -rf dist/*

      - name: Download wheel
        uses: actions/download-artifact@v4
        with:
          path: dist
          merge-multiple: true
          pattern: wheel-*

      - name: Show wheels
        run: ls -lha dist

      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/scalellm-*.whl
          tag_name: ${{ inputs.tag }}
          generate_release_notes: true
          draft: false
          prerelease: false
          make_latest: true

      - name: Clone whl repo
        run: |
          git clone https://oauth2:${WHL_TOKEN}@github.com/vectorch-ai/whl.git
        env:
          WHL_TOKEN: ${{ secrets.WHL_TOKEN }}

      - name: Append new whls into whl index
        run: |
          cd whl
          python ./publish_whl.py --whl_path=../dist

      - name: Commit whl index change
        run: |
          cd whl
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "Update whl index for version ${{ inputs.tag }}"
          git push
