name: Publish cpp images
on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to build and push'
        required: true
        type: string

  workflow_call:
    inputs:
      tag:
        description: 'Tag to build and push'
        required: true
        type: string
env:
  # Tells where to store caches.
  CI_CACHE_DIR: ${{ github.workspace }}/../../ci_cache

jobs:
  publish_gateway:
    runs-on: [self-hosted, linux]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and push gateway
        uses: docker/build-push-action@v5
        with:
          context: ./gateway
          push: true
          no-cache: true
          tags: |
            vectorchai/scalellm-gateway:${{ inputs.tag }}
            vectorchai/scalellm-gateway:latest

  publish_scalellm_cuda126:
    runs-on: [self-hosted, linux]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Build ScaleLLM for cuda 12.6
        timeout-minutes: 60
        run: |
          docker pull vectorchai/scalellm_devel:cuda12.6
          docker run --rm -t \
            -v "$CI_CACHE_DIR":/ci_cache \
            -v "$GITHUB_WORKSPACE":/ScaleLLM \
            -e VCPKG_DEFAULT_BINARY_CACHE=/ci_cache/.vcpkg/bincache \
            -e CCACHE_DIR=/ci_cache/.ccache \
            -u $(id -u):$(id -g) \
            vectorchai/scalellm_devel:cuda12.6 \
            bash /ScaleLLM/.ci/scripts/build_scalellm.sh

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and push scalellm docker image for cuda 12.6
        uses: docker/build-push-action@v5
        with:
          context: .
          file: .ci/docker/Dockerfile.scalellm
          push: true
          no-cache: true
          tags: |
            vectorchai/scalellm:${{ inputs.tag }}
            vectorchai/scalellm:latest

  publish_scalellm_cuda118:
    runs-on: [self-hosted, linux]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Build ScaleLLM for cuda 11.8
        timeout-minutes: 60
        run: |
          docker pull vectorchai/scalellm_devel:cuda11.8
          docker run --rm -t \
            -v "$CI_CACHE_DIR":/ci_cache \
            -v "$GITHUB_WORKSPACE":/ScaleLLM \
            -e VCPKG_DEFAULT_BINARY_CACHE=/ci_cache/.vcpkg/bincache \
            -e CCACHE_DIR=/ci_cache/.ccache \
            -u $(id -u):$(id -g) \
            vectorchai/scalellm_devel:cuda11.8 \
            bash /ScaleLLM/.ci/scripts/build_scalellm.sh

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and push scalellm for cuda 11.8
        uses: docker/build-push-action@v5
        with:
          context: .
          file: .ci/docker/Dockerfile.scalellm
          push: true
          no-cache: true
          tags: |
            vectorchai/scalellm_cu118:${{ inputs.tag }}
            vectorchai/scalellm_cu118:latest
